doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGO_URL)%'
            options: 
                {}
    default_database: '%env(resolve:MONGO_DB)%'
    document_managers:
        default:
            mappings:
                UserManagement:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/src/Module/UserManagement/Infrastructure/ReadModel/Mapping'
                    prefix: 'App\Module\UserManagement\Application\ReadModel'

when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes: false
        auto_generate_hydrator_classes: false
        document_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id: doctrine_mongodb.system_cache_pool

    framework:
        cache:
            pools:
                doctrine_mongodb.system_cache_pool:
                    adapter: cache.system
