doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        # 'App\Module\Auth\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Module/Auth/Infrastructure/Doctrine/Migrations'
        # 'App\Module\User\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Module/User/Infrastructure/Doctrine/Migrations'
        
    enable_profiler: false
