doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

        types:
            cost_item_status_enum: App\Module\CostManagement\Infrastructure\Doctrine\Types\CostItemStatusType
            unit_of_measure_enum: App\Module\ProductCatalog\Infrastructure\Doctrine\Types\UnitOfMeasureType

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Auth:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/src/Module/Auth/Infrastructure/Doctrine/Mapping"
                prefix: 'App\Module\Auth\Domain'
            UserManagement:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/src/Module/UserManagement/Infrastructure/Doctrine/Mapping"
                prefix: 'App\Module\UserManagement\Domain'
            ProductCatalog:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/src/Module/ProductCatalog/Infrastructure/Doctrine/Mapping"
                prefix: 'App\Module\ProductCatalog\Domain'
            CostManagement:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Module/CostManagement/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Module\CostManagement\Domain'
            SharedContext:
                type: xml
                is_bundle: false
                dir: "%kernel.project_dir%/src/Module/SharedContext/Infrastructure/Doctrine/Mapping"
                prefix: 'App\Module\SharedContext\Domain'
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
