# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler

    #esi: true
    #fragments: true
    router:
        default_uri: 'http://127.0.0.1:8000/'

when@dev:
    framework:
        http_client:
            default_options:
                verify_peer: false
                verify_host: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        error_controller: App\Module\Static\UI\Controller\ErrorTestController
