twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Module\Auth\Infrastructure\Twig\Components\: 'components/'
        App\Module\Admin\Infrastructure\Twig\Components\: 'components/'
        App\Shared\Infrastructure\Twig\Components\: 'components/'
