twig:
    form_themes:
        - 'form/layout.html.twig'
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates/tabler': 'Tabler'
        '%kernel.project_dir%/src/Module/Music/UI/Resources/views': 'MusicUI'
        '%kernel.project_dir%/src/Module/ProductCatalog/UI/Resources/templates': 'ProductCatalog'
        '%kernel.project_dir%/src/Module/CostManagement/UI/Resources/templates': 'CostManagement'
        '%kernel.project_dir%/src/Module/Sales/UI/Resources/templates': 'SalesModule'

babdev_pagerfanta:
  default_view: twig
  default_twig_template: 'default/_pagination.html.twig'

when@test:
    twig:
        strict_variables: true
