twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        # App\Shared\UI\Twig\Components\: 'components/'
        # App\Module\Music\UI\Twig\Components\: '@MusicUI/components/'
