ux_icons:
    default_icon_attributes:
        width: 1.2em
        height: 1.2em
        style: 'position: relative;'
    ignore_not_found: true
    aliases:
        'tabler:save': 'tabler:device-floppy'
        'tabler:save-changes': 'tabler:device-floppy'

    iconify:
        enabled: true
