ux_icons:
    default_icon_attributes:
        width: 1.2em
        height: 1.2em
        style: 'position: relative;'
    ignore_not_found: true
    aliases:
        settings: 'lucide:settings'
        pencil: 'lucide:pencil'
        trash: 'lucide:trash-2'
        eye: 'lucide:eye'
        check: 'lucide:check'
        moon: 'lucide:moon'
        sun: 'lucide:sun'
        'circle-half': 'bi:circle-half'
        'tabler:save-changes': 'tabler:device-floppy'

    iconify:
        enabled: true
