when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:

when@test:
    zenstruck_foundry:
        global_state:
            - Tests\Story\UserStory
        orm:
            reset:
                mode: schema
