when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        instantiator:
            use_constructor: false
        make_factory:
            add_hints: false
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true

when@test:
    zenstruck_foundry:
        global_state:
            - Tests\Story\UserStory
        orm:
            reset:
                mode: migrate
        mongo:
            reset:
                document_managers:
