workers:
    sass:
        cmd: ['symfony', 'console', 'sass:build', '--watch']

    messenger_consume_async_priority_low:
        cmd: ['symfony', 'console', 'messenger:consume', 'async_priority_low']
        watch: ['config', 'src', 'templates', 'vendor']

    messenger_consume_async_events:
        cmd: ['symfony', 'console', 'messenger:consume', 'async_events']
        watch: ['config', 'src', 'templates', 'vendor']

    docker_compose: ~

http:
    no_tls: true
