workers:
    sass:
        cmd: ['symfony', 'console', 'sass:build', '--watch']

    # messenger_consume_async_priority_low:
        # cmd: ['symfony', 'run', '-d', '--watch=config,src,templates,vendor/composer/installed.json', 'symfony', 'console', 'messenger:consume', 'async_priority_low', '-vv']

    messenger_consume_async:
        cmd: ['symfony', 'console', 'messenger:consume', 'async_events']
        watch: ['config', 'src', 'templates', 'vendor']

    docker_compose: ~

http:
    no_tls: true
